### ISSUE TITLE
Converting models built with Python 2, using Python 3

### ISSUE THREAD

**Issue by snormore** [triagemd/ml-tools#11]
```
$ keras_to_tensorflow .cache/best_res_450.hdf5 .cache/tf_best_res_450
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/bin/keras_to_tensorflow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/snormore/Workspace/triage/ml-tools/bin/keras_to_tensorflow", line 10, in <module>
    KerasToTensorflow.convert(sys.argv[1], sys.argv[2])
  File "/Users/snormore/Workspace/triage/ml-tools/ml_tools/keras_to_tensorflow.py", line 19, in convert
    model = KerasToTensorflow.load_keras_model(model_path)
  File "/Users/snormore/Workspace/triage/ml-tools/ml_tools/keras_to_tensorflow.py", line 13, in load_keras_model
    'DepthwiseConv2D': keras.applications.mobilenet.DepthwiseConv2D
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/models.py", line 233, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/models.py", line 307, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/engine/topology.py", line 2450, in from_config
    process_layer(layer_data)
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/engine/topology.py", line 2419, in process_layer
    custom_objects=custom_objects)
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/layers/core.py", line 694, in from_config
    function = func_load(config['function'], globs=globs)
  File "/Users/snormore/Workspace/triage/ml-tools/.venv/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 200, in func_load
    code = marshal.loads(code.encode('raw_unicode_escape'))
ValueError: bad marshal data (unknown type code)
```

cc @stephensolis

**Comment by stephensolis** [comment]
Looks like this is because of the `Lambda` layers in `to_multi_gpu` (eg: https://github.com/triagemd/skin-non-skin/blob/f1eb3f938bd032d8bde47035709a228fb3a7854f/code/2way.py#L92). 
The error is because of course bytecode format in Python 2 and 3 are different.

Therefore, the best fix is to modify the model export code in all our AI repos to not export the `to_multi_gpu`-related layers, and let the AI team know that's necessary for snapshot versions of the models. As a nice side effect, https://github.com/triagemd/ml-tools/blob/master/ml_tools/keras_to_tensorflow.py#L18 goes away.

I don't think it would be difficult to put together a quick-and-dirty hdf5 reader thing to check for the presence of those layers (via string search or something, without actually importing in Keras) and fail uploads if so as part of checks in the lab app. 
Thinking about this more, it might be easier to just have the lab app try to run a model import in Python 2 and 3 virtualenvs and fail if either throws.

An alternative approach would be to put together a quick-and-dirty hdf5 *writer* to try to strip out these layers without running a Keras import. I don't like the idea, though.

**Comment by stephensolis** [comment]
Fixed by https://github.com/triagemd/model-converters/pull/2
